//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.PowerPlatform.UIAutomation.Sample {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class PowerPlatformAdminCenter : global::System.Configuration.ApplicationSettingsBase {
        
        private static PowerPlatformAdminCenter defaultInstance = ((PowerPlatformAdminCenter)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PowerPlatformAdminCenter())));
        
        public static PowerPlatformAdminCenter Default {
            get {
                return defaultInstance;
            }
        }
    }
}
